### PR TITLE
Fix build workflow, bump min version to v12, add `v` tag removal

### PR DESCRIPTION
**Pull request by MrVauxs**

### CODE REVIEW

**Comment by typhonrt** [comment]
TRL works on v10-12 and folks can adjust the template to their needs. Granted I had no time to put up info in the main readme and I will.

Also we should create a separate template repo for symlink `dist` output direction. This one is "easier" to install directly in `Data/modules` and get started without the extra ceremony. 

I can make this the symlink repo I suppose and continue looking at the PRs in an hour or so.

**Comment by MrVauxs** [comment]
> TRL works on v10-12 and folks can adjust the template to their needs. Granted I had no time to put up info in the main readme and I will.

The types are explicitly v12, nor is anyone even developing for v10 anymore to be making a new module for that version. From a TS template no less.

> Also we should create a separate template repo for symlink `dist` output direction. This one is "easier" to install directly in `Data/modules` and get started without the extra ceremony.

This change does not do that! This purely fixes the non-existent `npm run build-dist` that you had in your github workflow, putting the generated Vite files into a `dist` directory. This directory is **NOT** symlinkable.

```yaml
      # Build distribution.
      - run: npm run build-dist

      # Create a zip file with all files required by the module to add to the release.
      - run: zip -r ./module.zip module.json dist/ lang/ packs/ LICENSE AUTHORS
 ```

**Comment by typhonrt** [comment]
I haven't had a chance to look in detail. Most of these problems especially with the GH workflow is that this repo was created 3 years ago and was stagnant / private until I revived it. I wanted to just get this out as early as possible and over the weekend in case some folks had time to take a look. So it does need some love on the periphery. So this is not like a it's 100% completed or vetted as this is the best form that a starter template can be in.. IE I just worked on getting the source code example together, but ran out of steam after a ~16 hour coding session.

It can be really helpful to collaborate on the README and communicating info regarding project setup and other aspects.

**Comment by MrVauxs** [comment]
I can add such a description in a separate PR although it hasn't changed from base "put in module directory, run `npm run build`, then `npm run dev`". The other PR addresses some of the pain points to starting off as well.

For now though I just wanted to make the template actually work in its complete form. So merging it sooner rather than later would be preferable.

The diff is unfortunately a giant block due to yaml formatting adding spaces.

**Comment by typhonrt** [comment]
I'm all for merging and sorting things out after the fact. It does look like both PRs you posted may have conflicts / touch the same files. I assume this one is the correct one and the other PR should be closed? Looks like you last touched this one quite recently.

Perhaps put everything into this PR and let me know when it's ready.

**Comment by MrVauxs** [comment]
No, the other PR simply includes this one as it originates from this branch. Please see the commits.

Merge this one first and then the other one if you want the improvements. I didn't want to pack everything into one PR if you felt the file name-changing plugin was unnecessary for the template.

chrome_2zHUqCkoHt

**Pull request merged**
